### ISSUE TITLE
Test Shell 커맨드패턴 적용

### ISSUE THREAD

**Issue by OddEye1022** [arkdusdyk/CRA_SSDProject#103]
![image](https://github.com/arkdusdyk/CRA_SSDProject/assets/150755365/e8dd02f9-8b49-4017-8263-6a7f0d59f445)

**Comment by OddEye1022** [comment]
![image](https://github.com/arkdusdyk/CRA_SSDProject/assets/150755365/227558e0-ffa2-4187-a64a-0af58e549478)

![image](https://github.com/arkdusdyk/CRA_SSDProject/assets/150755365/46c288cc-3692-47d8-9fcf-678b92124156)

![image](https://github.com/arkdusdyk/CRA_SSDProject/assets/150755365/4abac0a4-b047-4481-9d7d-12d857e48942)

![image](https://github.com/arkdusdyk/CRA_SSDProject/assets/150755365/28f9b1d4-c366-4ed0-bf61-2b61b008c726)

**Comment by arkdusdyk** [comment]
내용 확인했습니다 감사합니다!
