### ISSUE TITLE
Test Shell (TDD & Mock)

### ISSUE THREAD

**Issue by OddEye1022** [arkdusdyk/CRA_SSDProject#104]
![image](https://github.com/arkdusdyk/CRA_SSDProject/assets/150755365/19468c3d-7d41-4f9c-b7a7-777f14739a0e)

![image](https://github.com/arkdusdyk/CRA_SSDProject/assets/150755365/6f3cef36-4d09-4010-a7ff-f5ff17903b47)

![image](https://github.com/arkdusdyk/CRA_SSDProject/assets/150755365/8cd40f64-80cf-4b8a-8e5f-779be7cf94b6)

![image](https://github.com/arkdusdyk/CRA_SSDProject/assets/150755365/5fad12aa-3ab4-425b-8646-8300dcf75c1b)

**Comment by OddEye1022** [comment]
![image](https://github.com/arkdusdyk/CRA_SSDProject/assets/150755365/5b4591ec-f117-4a97-bda1-124d86e33059)

**Comment by arkdusdyk** [comment]
작성 한 부분인데, 미리 말씀드렸어야했는데 죄송합니다!
감사합니다!
