### ISSUE TITLE
Logger 관련 Clean code 작업

### ISSUE THREAD

**Issue by kwonluck** [arkdusdyk/CRA_SSDProject#96]
![image](https://github.com/arkdusdyk/CRA_SSDProject/assets/170284023/25b9dd46-a821-4b96-be76-2084f3d4aad6)

![image](https://github.com/arkdusdyk/CRA_SSDProject/assets/170284023/61f8045a-7688-4abe-96ab-61f966ed2da1)

**Comment by arkdusdyk** [comment]
확인했습니다
감사합니다
